[package]
name = "aws-client-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
ureq = "3.0.12"
sha2 = "0.10.9"
hmac = "0.12.1"
chrono = "0.4.41"
xmltree = "0.11.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
