[package]
name = "aws-client-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
ureq = "3.1.2"
sha2 = "0.10.9"
hmac = "0.12.1"
chrono = "0.4.42"
xmltree = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
