[package]
name = "aws-client-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = "2.10.1"
sha2 = "0.10.8"
hmac = "0.12.1"
chrono = "0.4.38"
xmltree = "0.11.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
